CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS wordpress@localhost IDENTIFIED BY 'wordpress';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;
FLUSH PRIVILEGES;